### ISSUE TITLE
стр статистика2 - блок отчет должен открываться по нажатию кнопки "применить"

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-sinergo#19]
1. кнопку "сохранить" заменить на "применить"
2.http://prntscr.com/l9sk94 - заменить на "пользователи" и "тесты"
3. блок отчет изначально скрыт, раскрывается по нажатию на "применить"
4. выпадающие списки дожны быть с чекбоксами http://prntscr.com/l9slo5

**Comment by SeregaWeb** [comment]
блока вообще не будет существовать пока бэк не отдаст отчет , это не моя проблема , чекбоксы я сделал

**Comment by VladyslavKovalchuk** [comment]
исправить текст (кнопку "сохранить" заменить на "применить"
2.http://prntscr.com/l9sk94 - заменить на "пользователи" и "тесты")
