### ISSUE TITLE
добавить что-небудь в фавикон

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-sinergo#38]
например s с лого

**Comment by MalahVitalij** [comment]
Что-то невидно ни на одной из страник фавиконов
http://joxi.ru/nAyYOv4cYMMWaA
http://joxi.ru/8AnzQEeUjGG8XA
и т.д.

**Comment by SeregaWeb** [comment]
на сервер не залилась , уже сделал
