### ISSUE TITLE
не работает удаление вопросов

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-sinergo#49]
в попапе http://prntscr.com/lk4vsa, кнопкой работает

**Comment by VladyslavKovalchuk** [comment]
кнопка отменить тоже не работает так, как описано в ТЗ http://prntscr.com/lk4wpw
http://prntscr.com/lk4x64

**Comment by maxis55** [comment]
Добавил туда ссылку, но фронту нужно посмотреть, чтобы работало так, как описано

**Comment by maxis55** [comment]
Не знаю, что первый комментарий означает

**Comment by VladyslavKovalchuk** [comment]
не удаляется, если нажимать на кнопку удалить в выпадающем блоке справа (не на иконку ведра вверху) http://prntscr.com/ll6dp9

**Comment by VladyslavKovalchuk** [comment]
на стр вопросы и группы вопросов удаление работает нормально и иконкой корзины, и по нажатию на текст удалить в раскрывающемся блоке справа. На стр создание вопроса в группе по нажатию кнопки "отменить" и в появившемся попапе "да" либо "нет" ничего не происходит, не отменяется создание вопроса, не удаляется таким образом. (кнопка отменить тоже не работает так, как описано в ТЗ http://prntscr.com/lk4wpw
http://prntscr.com/lk4x64)

**Comment by maxis55** [comment]
Убрал опечатку, по-этому сейчас удаляет, но потом перенаправляет
