### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [MalahVitalij/rocket-sinergo#52]
http://prntscr.com/lk5i1t - ничего не происходит и http://prntscr.com/lk5ibg, ничего не происходит и http://prntscr.com/lk5jyh (всеравно создается, так же как и сохранить)

**Comment by maxis55** [comment]
Попапа не было даже на вёрстке для третьего скрина

**Comment by VladyslavKovalchuk** [comment]
то что на 1 скрине, исправлено, остальное осталось так же

**Comment by maxis55** [comment]
второе исправлено, третье всё еще нужно верстальщику прикрутить попап

**Comment by VladyslavKovalchuk** [comment]
сейчас то что на втором скрине просто перебрасывает на предыдущую страницу, потому нужно править текст в попапе на что-то типа "вы уверенны что хотите отменить?", по нажатию должно отменяться все, что изменилось после последнего сохранения (если добавлялись вопросы и не нажималась соседняя кнопка сохранить, но нажали отменить, то добавленные вопросы удаляются)
